### ISSUE TITLE
Invariant Violation: How to work with 100% width/height?

### ISSUE THREAD

**Issue by v0lume** [alexZajac/react-native-skeleton-content#6] opened 2019-12-05 22:11 UTC
Trying to set value of height/width of layout element to 100% - throws an error
```
Invariant Violation <<NaN>> is not usable as a native method argument
```
![image](https://user-images.githubusercontent.com/5075100/70278391-3ac1d880-17c5-11ea-8cf4-35422c7cedf8.png)

**Comment by rs4231199** [comment] 2019-12-07 14:30
```js
import { Dimensions } from 'react-native';
const screenWidth = Dimensions.get('window').width;
```
I needed to set width equal to screen-width.

**Comment by v0lume** [comment] 2019-12-09 13:37
@rs4231199 yes it works, but I think it's not a good solution, more like workaround

**Comment by ItsSander107** [comment] 2019-12-11 13:02
I'd love this to be a thing. My current width is `Dimensions.get('window').width - constants.styleSettings.paddedView * 2,`. `'100%'` is a tad shorter.

**Comment by alexZajac** [comment] 2019-12-17 15:59
Hey @v0lume!
The issue is happening because since we are passing the child width/height properties to the transform property, it throws an error because the transfrom can't accept a percentage. 
As @rs4231199 suggested, a quick workaround would be to init the desired witdh/height in a variable for each child having a different width/height.

I am currently searching for a solution to this problem, and I'll get back to you in the next few days.

**Comment by alexZajac** [comment] 2020-06-06 21:21
Hello guys, I have added support for percentages in the latest version (1.0.16). Closing the issue for now, and feel free to check it out and send your feedback!

**Closed as completed by alexZajac** 2020-06-06 21:21 UTC
Labels: bug
